language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y spatialite-bin binutils libproj-dev gdal-bin
install:
- pip install django djangorestframework
script: python manage.py test
notifications:
  slack:
    secure: A60Ro7fgmXNc0TF7kiNt7nFIsKZNgSt1qmBaemIbiAkmF/0zcZRb92wchBoqmTGTRw5lLnL7/b23X4qB/hjRyPTsTahyVWRt8ZYMDp+KK2Sp6cvPf/Pl/p/cfFf2wLQKEKH//MOM4gKYiJJgAqyx7WtwgMxQ7286wymoKOXJRYE9NErUJLuue9d90k1/xJO4sOTXZJG5nNnX4/jLMxbhWO/kYOVtoecty/7V7MnBvJd8A3MBJUfbMgKdNY1UN/dObubNvctqSjzi6cxk1mSaq0fYDPXRkZFyXe50QBD5o9aeG5qVJWe6MKQTwow0r5GX8610J48rOvb6krecv8xbvTrJ1E6YEKeGdpLwS1NQeZCm9QzFJrVjL/TA2kqbtnzHBUD4V1/eVu0CC0aLnW3D1q0mDTqVznwTImDtPtIgepEpcElc0VVb9slzscpTETEWC5A2uoPVHA3Lne8gb8CJqkdfCujllrGCCdyJZ4rvp57xfvNu8AoNsAxhsgJumFHxYiRHHrTclFnxUep7r3eYpUW8EP5sqHe2UUbdux9PRFWqJAfepoQKfRIDmyZNJjHQIwK5k+Vad6I4WjQVswuTvyCdR90Q1Mb+tzi9TUXNoilMrzKAGHQhORdh2HWrWCak315pYfLuM45gccnaqMr/0OTOKpJHrPaGJPNYkDiXttY=
