# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest-auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='num_seats',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Number of Car seats'),
        ),
    ]
