# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest-auth', '0002_auto_20170830_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Suspended account?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
