# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest-auth', '0003_auto_20170913_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_suspension',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Suspension'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Suspended until'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
